### ISSUE TITLE
Can't Post Videos 

### ISSUE THREAD

**Issue by younis207** [YezerSTN/INSSIST#1]
After every upload says can't post
+ there wasn't a popup says 
Sorry, this page isn't available.
The link you followed may be broken, or the page may have been removed. [Go back to Instagram.](https://www.instagram.com/) 
Before waiting for fix :D 
I Tried The original one works normally idk where is the proplem I tried To remove chrome and extensions folder same isuue

**Comment by younis207** [comment]
+ Waiting For ver 23.2.1

**Comment by YezerSTN** [comment]
Is that you have tried the new version of INSSIST that corrected the error.
The new version they have released is (23.2.1) which I have not cracked. I will crack it and the problem of "posting videos" will be solved.

**Comment by YezerSTN** [comment]
I have already uploaded the new cracked version.
Try it and let me know if you have the same problem.

https://github.com/YezerSTN/INSSIST/releases/tag/v23.2.1

**Comment by younis207** [comment]
It works dude
Great Work I really appreciate it
