### ISSUE TITLE
Direct Messages Not Loading

### ISSUE THREAD

**Issue by turtl3sku11** [YezerSTN/INSSIST#11]
Sometimes the DMs Inbox doesn't load, sometimes it works but its just a few hours and then it says an error occured. Please solve this, is really annoying and also I can't see stories because some of them don't load either and it's not my internet. And everything happens at the same time.

**Comment by thaksharaaa** [comment]
> Sometimes the DMs Inbox doesn't load, sometimes it works but its just a few hours and then it says an error occured. Please solve this, is really annoying and also I can't see stories because some of them don't load either and it's not my internet. And everything happens at the same time.

don't tell him to Fix the issues of extension cuz he is not the developer lol

**Comment by YezerSTN** [comment]
@thaksharaaa you are right, I just steal or edit all your code to get your premium benefits.

**Comment by YezerSTN** [comment]
@turtl3sku11 Try this new cracked version, it's a great update and fix. 

https://github.com/YezerSTN/INSSIST/releases/tag/v23.6.6

**Comment by turtl3sku11** [comment]
oop- sorry and tysm!
