### ISSUE TITLE
Please update the Version to 23.6.10

### ISSUE THREAD

**Issue by Thakshara9728** [YezerSTN/INSSIST#15]
Please update the Version to 23.6.10 cuz the Current one cant upload Reels.Thank you

**Comment by YezerSTN** [comment]
working....

**Comment by YezerSTN** [comment]
https://github.com/YezerSTN/INSSIST/releases/tag/v23.6.10

**Comment by Thakshara9728** [comment]
Thank you my man.Thank you❤️
