### ISSUE TITLE
No reels option

### ISSUE THREAD

**Issue by trigonidontknowhowtouse** [YezerSTN/INSSIST#2]
![Screenshot 2022-09-10 135747](https://user-images.githubusercontent.com/105162342/189475449-541ba01d-009d-4af6-90a3-e76895a156b6.png)
there is no reels option while uploading yezer can you help ??????

**Comment by YezerSTN** [comment]
Hi, sorry for taking so long, I've been busy.

But could you tell me what browser you are using?
And the version of INSSIST you are using?

**Comment by cops12** [comment]
me too not showing reel option....location INDIA

**Comment by YezerSTN** [comment]
Instagram's platform limits Reels to 50 countries, including the United States.

I believe INSSIST cannot post reels from INDIA.
