### ISSUE TITLE
Cant tap plus button

### ISSUE THREAD

**Issue by scorpionx565br** [YezerSTN/INSSIST#20]
Error Upload

**Comment by hiteshop090123** [comment]
me toooo

**Comment by Denjimano** [comment]
i have the same problem

**Comment by Nikitos18667** [comment]
Тоже не могу добавить 2 ролик к сторис

**Comment by Nikitos18667** [comment]
Also I can't add 2 videos to stories

**Comment by YezerSTN** [comment]
https://github.com/YezerSTN/INSSIST/releases/tag/v23.7.3

**Comment by Nikitos18667** [comment]
> https://github.com/YezerSTN/INSSIST/releases/tag/v23.7.3

File
~\Desktop\INSSIST-main (1)
Error
The manifest file is missing or unreadable
Failed to load manifest.

pop up on click load unpacked extension

**Comment by Nikitos18667** [comment]
> https://github.com/YezerSTN/INSSIST/releases/tag/v23.7.3

there is still no + button to add a second or more stories

**Comment by Nikitos18667** [comment]
Yes thank you very much it works!!!!

**Comment by Denjimano** [comment]
i have an issuse when i upload video "Uploading video cancelled. Please ensure that the video is 1 second to 15 minutes long and the size ratio is less than 1.91:1" and i was upload video like that "1920*1080"befour the update.

**Comment by YezerSTN** [comment]
try this version

https://github.com/YezerSTN/INSSIST/releases/tag/v24.0.2
