### ISSUE TITLE
cant post reels 

### ISSUE THREAD

**Issue by cops12** [YezerSTN/INSSIST#3]
not showing reels option on there

**Comment by YezerSTN** [comment]
Where does it not appear?
![image](https://user-images.githubusercontent.com/109930585/191365923-d212f4ff-4eb5-4365-b08a-aca1978805ce.png)

**Comment by celozaga** [comment]
This is because Instagram has a new UI in test for some users, so the extension not work with the new layout

**Comment by celozaga** [comment]
![image](https://user-images.githubusercontent.com/69090827/191367035-ae51299a-e3cc-42bf-9da1-39565671e1f8.png)

The new UI.

**Comment by YezerSTN** [comment]
In the "Create" button does not give you the option to reel?

**Comment by YezerSTN** [comment]
With this link you can access the extension;
https://app.inssist.com/

Try if you can upload reels there

**Comment by celozaga** [comment]
> In the "Create" button does not give you the option to reel?

Nop, just open the default post modal.

**Comment by celozaga** [comment]
> With this link you can access the extension; https://app.inssist.com/
> 
> Try if you can upload reels there

the official version works, apparently cracked needs a update. 
![image](https://user-images.githubusercontent.com/69090827/191370759-bd7d8059-72d8-488e-bc33-f015f365ffb8.png)

**Comment by YezerSTN** [comment]
I am working on version 23.3.5.
I will upload it today.

**Comment by celozaga** [comment]
> I am working on version 23.3.5. I will upload it today.

Thank you! 

Btw, is possible to upload reels longer than 60 seconds, like 90s? or the Reels API still only support 60s?

**Comment by YezerSTN** [comment]
It only goes up to 60. I have not tried 90.

**Comment by YezerSTN** [comment]
https://github.com/YezerSTN/INSSIST/releases/tag/v23.3.5

This new version is now functional with the new Instagram interface.

**Comment by celozaga** [comment]
> 

Yes thanks, already updated.
