### ISSUE TITLE
post button not working

### ISSUE THREAD

**Issue by PastelBeltran** [YezerSTN/INSSIST#4]
<img width="1420" alt="Captura de Pantalla 2022-09-23 a la(s) 01 35 02" src="https://user-images.githubusercontent.com/114212789/191904262-8283b1ad-7b33-4c8d-a68f-97bc42c028ad.png">

 Hola! cuando sitúo el click encima del botón posting noto que el link está caído "#" (adjunto imagen). Esto es correcto? 

Agradezco enormemente tu aporte, valoro mucho tu trabajo. ¡Gracias!

**Comment by YezerSTN** [comment]
Mientras funcione correctamente, si.
Y gracias por el comentario positivo. <3
