### ISSUE TITLE
A issue faced by the users to be not able to upload video

### ISSUE THREAD

**Issue by montipapa** [YezerSTN/INSSIST#40]
Subject: Issue with Extension Upload

Dear YezerSTN,

We are facing an uploading issue with your extension, and we're unable to upload files. Please fix it as soon as possible.

Thank you.

Sincerely,
montipapa

**Comment by elfychan** [comment]
i am having the same problem

**Comment by YezerSTN** [comment]
I have already uploaded the new update on 04/20/23. I hope it won't give you the same problem, let me know if you have any other problem.

Here; https://github.com/YezerSTN/INSSIST/releases/tag/v24.0.2
