### ISSUE TITLE
you should help us 

### ISSUE THREAD

**Issue by kadri889** [YezerSTN/INSSIST#42]
you need to give us new verision because the last one is terrible you can't  upload vedio story he says must be under something and i think you cannot upload reels i know its difficult to work on new verision but we need it so mush help us pls

**Comment by YezerSTN** [comment]
Hello, I apologize for not having uploaded the new version, I've been busy, but I hope to be more active and to be able to continue bringing the new versions, meanwhile here I leave the new version;
https://github.com/YezerSTN/INSSIST/releases/tag/v24.0.2
