### ISSUE TITLE
Under the post later, There is no Schedule option. 

### ISSUE THREAD

**Issue by Iamabrarahmed** [YezerSTN/INSSIST#47]
Can you please help with the
![Capture](https://github.com/YezerSTN/INSSIST/assets/48677878/344da365-d806-4577-8f63-edc266495e50)
 issue. This will be of great help. Thank you.

**Comment by Iamabrarahmed** [comment]
The Bulk Scheduler is the best thing. It is not visible. Can you please add it?

**Comment by YezerSTN** [comment]
try this new version https://github.com/YezerSTN/INSSIST/releases/tag/v25.0.1

![image](https://github.com/YezerSTN/INSSIST/assets/109930585/7fcfa142-c51d-45a0-a895-d3575811ffd2)

**Comment by Iamabrarahmed** [comment]
Thank you
