### ISSUE TITLE
home page tools gone 

### ISSUE THREAD

**Issue by mystt6ix** [YezerSTN/INSSIST#52]
yk how ders a home page button post button nd all dat, its like gone theres just da home page and all other tools jus gone 
![image](https://github.com/YezerSTN/INSSIST/assets/136399416/ad44228e-83d2-42e8-8b84-c21cbc69dc09)
see there at da bottom all da tools gone

**Comment by YezerSTN** [comment]
test the new version

https://github.com/YezerSTN/INSSIST/releases/tag/v26.0.2
