### ISSUE TITLE
Upgrade to Pro Error

### ISSUE THREAD

**Issue by Frankyfit86** [YezerSTN/INSSIST#58]
When I want to change the time of my schedule always comes the message: Upgrade to PRO.
So I can not change the time.
Although I see "PRO ACTIVATED 🏅" in the options.

**Comment by YezerSTN** [comment]
https://github.com/YezerSTN/INSSIST/releases/tag/v26.0.2 
I updated the repository and now you can schedule the posts, you will have to download the extension again.

The "PRO ACTIVATED 🏅" message will no longer appear in this update. But if you have problems again, do not hesitate to let me know.

**Comment by YezerSTN** [comment]
This is the new version, I have already tested it and corrected the error.

Version; https://github.com/YezerSTN/INSSIST/releases/tag/v26.2.4

Note: Give me a star so I can send you the new versions :)
