### ISSUE TITLE
Tells me to upgrade to pro

### ISSUE THREAD

**Issue by mystt6ix** [YezerSTN/INSSIST#60]
![image](https://github.com/YezerSTN/INSSIST/assets/136399416/ed858dd8-6dc6-4d2c-a588-da9355c5a910)

**Comment by YezerSTN** [comment]
This is the new version, I have already tested it and corrected the error.

Version; https://github.com/YezerSTN/INSSIST/releases/tag/v26.2.4

Note: Give me a star so I can send you the new versions :)
