### ISSUE TITLE
upload failed on INSSIST

### ISSUE THREAD

**Issue by 2022Sius** [YezerSTN/INSSIST#7]
Hi, one issue this morning, upload failed through story, reels. thanks for your big help
using microsoft edge

**Comment by Batman2707** [comment]
true

**Comment by Batman2707** [comment]
> Hi, one issue this morning, upload failed through story, reels.

**Comment by roberto571** [comment]
same ;(

**Comment by Nikitos18667** [comment]
It turns out I'm trying to upload history to INSSIST pro today, but it says that the upload failed. What can I do to help?

**Comment by Nikitos18667** [comment]
on the 19th I published a story where everything is fine and yesterday I wanted to publish and knocks out an error could not load the story

**Comment by faforid** [comment]
me too! I can't even login. both crack and original one. I think the trouble is from INSSIST itself. I got this error message.

"There was a problem logging you into Instagram. Please try again soon."

**Comment by Nikitos18667** [comment]
> я тоже! Я даже не могу войти. и кряк и оригинал. Думаю, беда от самого INSSIST. Я получил это сообщение об ошибке.
> 
> «Возникла проблема со входом в Instagram. Повторите попытку позже».

со входом в Инстаграм я Решил проблему очистил историю Гугл Хрома За всё время

**Comment by Nikitos18667** [comment]
and the error with the publication of the story did not disappear

**Comment by faforid** [comment]
> and the error with the publication of the story did not disappear

yeah after login, I still can't upload story dan reels :(

**Comment by Nikitos18667** [comment]
> > и ошибка с публикацией истории не исчезла
> 
> да, после входа в систему я все еще не могу загрузить сюжетные ролики :(

Well, this is already a mistake in INSSIST itself.

**Comment by YezerSTN** [comment]
I also had problems, but INSSIST has uploaded a new version (23.4.3). So now it's time to crack it, I will upload it in the next hours.

I hope it will solve your problems.

**Comment by YezerSTN** [comment]
Try this version and let me know if you still have the same problems.

https://github.com/YezerSTN/INSSIST/releases/tag/v23.4.3

**Comment by Nikitos18667** [comment]
> Try this version and let me know if you still have the same problems.
> 
> https://github.com/YezerSTN/INSSIST/releases/tag/v23.4.3

Yes it works, thank you very much!

**Comment by 2022Sius** [comment]
> Try this version and let me know if you still have the same problems.
> 
> https://github.com/YezerSTN/INSSIST/releases/tag/v23.4.3

Thanks for the help, works fine

**Comment by 2022Sius** [comment]
> Try this version and let me know if you still have the same problems.
> 
> https://github.com/YezerSTN/INSSIST/releases/tag/v23.4.3

another problem appeared, story played but can't be seen, thanks

**Comment by Nikitos18667** [comment]
The application works for me, but I click, for example, on adding my story, it takes a long time to load, it doesn’t load at all

**Comment by Nikitos18667** [comment]
Application lags
