### ISSUE TITLE
Stories bug = pics in weird filter, videos not showing.

### ISSUE THREAD

**Issue by georgebg1** [YezerSTN/INSSIST#8]
Also, when you scroll just a tad on direct messages tab it bugs out and says ''sorry this page isn't available''.

**Comment by georgebg1** [comment]
> Try uninstalling all versions of INSSIST completely and then install the latest version.

that fixed it, thanks. BTW when I scroll down on direct messages, it bugs out and shows this page isn't available, so you can't look at old chats. Is that issue on their end?

**Comment by YezerSTN** [comment]
I think it's an INSSIST bug and they will fix it in the next updates, in the meantime I recommend you to look for the chat and not to scroll down.

**Comment by YezerSTN** [comment]
Try this version;

https://github.com/YezerSTN/INSSIST/releases/tag/v23.4.4

**Comment by YezerSTN** [comment]
Try this new cracked version, it's a great update and fix. 

https://github.com/YezerSTN/INSSIST/releases/tag/v23.6.6
