### ISSUE TITLE
I cant upload story

### ISSUE THREAD

**Issue by tasha-dev** [YezerSTN/INSSIST#84]
Hey there
i found this little bug or something that even though i done all the stuff , i cannot upload stories and it says "A trial period of this feature has expired. Please consider upgrading to PRO to continue using Video Stories.
"

**Comment by Ajnus** [comment]
> Hey there i found this little bug or something that even though i done all the stuff , i cannot upload stories and it says "A trial period of this feature has expired. Please consider upgrading to PRO to continue using Video Stories. "

And what a funny error that is.
> PRO is Active!
> Activate PRO

![Captura de tela de 2024-05-11 19-47-27](https://github.com/YezerSTN/INSSIST/assets/8205907/edaf7c36-3219-408b-933f-3a4917552d5b)

**Comment by tasha-dev** [comment]
> > Hey there i found this little bug or something that even though i done all the stuff , i cannot upload stories and it says "A trial period of this feature has expired. Please consider upgrading to PRO to continue using Video Stories. "
> 
> And what a funny error that is.
> 
> > PRO is Active!
> > Activate PRO
> 
> ![Captura de tela de 2024-05-11 19-47-27](https://private-user-images.githubusercontent.com/8205907/329816705-edaf7c36-3219-408b-933f-3a4917552d5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDk3MjQsIm5iZiI6MTcxODQ0OTQyNCwicGF0aCI6Ii84MjA1OTA3LzMyOTgxNjcwNS1lZGFmN2MzNi0zMjE5LTQwOGItOTMzZi0zYTQ5MTc1NTJkNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTVUMTEwMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzcxMzBhNDJlOTA4YjNiMmMyN2YyMTA4Y2ZlZDg1MDI0NzljNDRjOGYwZTkzYTAyMDZjYjU3ODdhZTg1N2JhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G4u066o61mzCsoUXp2xPF_yeeH2cjXFXgX5YU-wmqeI)

I've changed my browser from chrome to arc and the error was gone. 
I Recommend you to do this

**Comment by Ajnus** [comment]
> > > Hey there i found this little bug or something that even though i done all the stuff , i cannot upload stories and it says "A trial period of this feature has expired. Please consider upgrading to PRO to continue using Video Stories. "
> > 
> > 
> > And what a funny error that is.
> > > PRO is Active!
> > > Activate PRO
> > 
> > 
> > ![Captura de tela de 2024-05-11 19-47-27](https://private-user-images.githubusercontent.com/8205907/329816705-edaf7c36-3219-408b-933f-3a4917552d5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDk3MjQsIm5iZiI6MTcxODQ0OTQyNCwicGF0aCI6Ii84MjA1OTA3LzMyOTgxNjcwNS1lZGFmN2MzNi0zMjE5LTQwOGItOTMzZi0zYTQ5MTc1NTJkNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTVUMTEwMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzcxMzBhNDJlOTA4YjNiMmMyN2YyMTA4Y2ZlZDg1MDI0NzljNDRjOGYwZTkzYTAyMDZjYjU3ODdhZTg1N2JhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G4u066o61mzCsoUXp2xPF_yeeH2cjXFXgX5YU-wmqeI)
> 
> I've changed my browser from chrome to arc and the error was gone. I Recommend you to do this

Works as well on Chromium (which Arc is based on)
