### ISSUE TITLE
Error uploading reels

### ISSUE THREAD

**Issue by Lofox18** [YezerSTN/INSSIST#9]
it shows error after processing a reel why does this happen every time i do so ? and why does it ask for API every time :/

**Comment by YezerSTN** [comment]
What version of INSSIST are you using?

And ask for the API to be able to process the reel and upload it.

**Comment by nibronib** [comment]
when i use inssist i was face problem in my instagram account like dosen't show my instagram website link, please fixed this problem.

**Comment by Lofox18** [comment]
> What version of INSSIST are you using?
> 
> And ask for the API to be able to process the reel and upload it.

actually its latest version that you shared.. i even tested removing and installing and

**Comment by YezerSTN** [comment]
Try this version;

https://github.com/YezerSTN/INSSIST/releases/tag/v23.4.4

**Comment by Lofox18** [comment]
> Try this version;
> 
> https://github.com/YezerSTN/INSSIST/releases/tag/v23.4.4

thank you so much .. it actually worked.. btw i tried contacting you on instagram but DMs are closed.. just wanted to say big thanks for this great help.. means alot
